path: /Users/darylroberts/Documents/Fullstack_Capstone/
train: train_data/images
val: test_data/images

names:
    0: articulated_truck
    1: bicycle
    2: bus
    3: car
    4: motorcycle
    5: motorized_vehicle
    6: non-motorized_vehicle
    7: pedestrian
    8: pickup_truck
    9: single_unit_truck
    10: work_van
